/*
 * The MIT License
 *
 * Copyright 2016 Claudinei Aparecido Perboni - contact:cperbony@gmail.com.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.bakeryfactory.vendas.cliente;

import org.openswing.swing.mdi.client.InternalFrame;

/**
 *
 * @author Claudinei Aparecido Perboni - contact:cperbony@gmail.com
 */
public class VendaCondicoesPagamentoDetalhe extends InternalFrame {
    
    private VendaCondicoesParcelasGridController condicoesParcelaGridController;

    /**
     * Creates new form ColaboradorDetalhe
     *
     * @param controller
     */
    public VendaCondicoesPagamentoDetalhe(VendaCondicoesPagamentoDetalheController controller) {
        initComponents();

        form1.setFormController(controller);
        
        condicoesParcelaGridController = new VendaCondicoesParcelasGridController(this);
        gridControlVendaParcelas.setController(condicoesParcelaGridController);
        gridControlVendaParcelas.setGridDataLocator(condicoesParcelaGridController);
    }

    /**
     *
     * @return FORM
     */
    public org.openswing.swing.form.client.Form getForm1() {
        return form1;
    }
    
    public org.openswing.swing.client.GridControl getGridControlVendaParcelas() {
        return gridControlVendaParcelas;
    }
    
    public VendaCondicoesParcelasGridController getCondicoesParcelasGridController() {
        return condicoesParcelaGridController;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanelVendaCondParcelas = new javax.swing.JPanel();
        insertButtonCondParcela = new org.openswing.swing.client.InsertButton();
        editButtonCondParcela = new org.openswing.swing.client.EditButton();
        deleteButtonCondParcela = new org.openswing.swing.client.DeleteButton();
        saveButtonCondParcela = new org.openswing.swing.client.SaveButton();
        reloadButtonCondParcela = new org.openswing.swing.client.ReloadButton();
        navigatorBarCondParcela = new org.openswing.swing.client.NavigatorBar();
        gridControlVendaParcelas = new org.openswing.swing.client.GridControl();
        integerColumn3 = new org.openswing.swing.table.columns.client.IntegerColumn();
        integerColumn4 = new org.openswing.swing.table.columns.client.IntegerColumn();
        decimalColumn5 = new org.openswing.swing.table.columns.client.DecimalColumn();
        form1 = new org.openswing.swing.form.client.Form();
        lblNome = new org.openswing.swing.client.LabelControl();
        textControl3 = new org.openswing.swing.client.TextControl();
        lblDescricao = new org.openswing.swing.client.LabelControl();
        lblFaturamentoMin = new org.openswing.swing.client.LabelControl();
        numericControl5 = new org.openswing.swing.client.NumericControl();
        lblFaturamentoMax = new org.openswing.swing.client.LabelControl();
        numericControl6 = new org.openswing.swing.client.NumericControl();
        lblIndiceCorrecao = new org.openswing.swing.client.LabelControl();
        numericControl7 = new org.openswing.swing.client.NumericControl();
        lblDiasTolerancia = new org.openswing.swing.client.LabelControl();
        numericControl8 = new org.openswing.swing.client.NumericControl();
        lblValorTolerancia = new org.openswing.swing.client.LabelControl();
        numericControl9 = new org.openswing.swing.client.NumericControl();
        lblPrazoMedio = new org.openswing.swing.client.LabelControl();
        numericControl10 = new org.openswing.swing.client.NumericControl();
        textAreaControl1 = new org.openswing.swing.client.TextAreaControl();
        jPanelVendaCondPagamento = new javax.swing.JPanel();
        editButtonCondPagto = new org.openswing.swing.client.EditButton();
        reloadButtonCondPagto = new org.openswing.swing.client.ReloadButton();
        saveButtonCondPagto = new org.openswing.swing.client.SaveButton();

        setTitle("Bakery Factory - Vendas e Faturamento");
        setPreferredSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanelVendaCondParcelas.setBorder(javax.swing.BorderFactory.createTitledBorder("Venda Condições Parcelas"));
        jPanelVendaCondParcelas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));
        jPanelVendaCondParcelas.add(insertButtonCondParcela);
        jPanelVendaCondParcelas.add(editButtonCondParcela);
        jPanelVendaCondParcelas.add(deleteButtonCondParcela);
        jPanelVendaCondParcelas.add(saveButtonCondParcela);
        jPanelVendaCondParcelas.add(reloadButtonCondParcela);
        jPanelVendaCondParcelas.add(navigatorBarCondParcela);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(jPanelVendaCondParcelas, gridBagConstraints);

        gridControlVendaParcelas.setAutoLoadData(false);
        gridControlVendaParcelas.setFunctionId("vendaCondicoesParcelas");
        gridControlVendaParcelas.setInsertRowsOnTop(false);
        gridControlVendaParcelas.setValueObjectClassName("com.bakeryfactory.vendas.java.VendaCondicoesParcelasVO");
        gridControlVendaParcelas.getColumnContainer().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        integerColumn3.setColumnName("parcela");
        integerColumn3.setEditableOnEdit(true);
        integerColumn3.setEditableOnInsert(true);
        integerColumn3.setHeaderColumnName("Parcela");
        integerColumn3.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridControlVendaParcelas.getColumnContainer().add(integerColumn3);

        integerColumn4.setColumnName("dias");
        integerColumn4.setEditableOnEdit(true);
        integerColumn4.setEditableOnInsert(true);
        integerColumn4.setHeaderColumnName("Dias a partir da venda");
        integerColumn4.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        integerColumn4.setPreferredWidth(130);
        gridControlVendaParcelas.getColumnContainer().add(integerColumn4);

        decimalColumn5.setColumnName("taxa");
        decimalColumn5.setDecimals(2);
        decimalColumn5.setEditableOnEdit(true);
        decimalColumn5.setEditableOnInsert(true);
        decimalColumn5.setHeaderColumnName("% da Parcela");
        decimalColumn5.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridControlVendaParcelas.getColumnContainer().add(decimalColumn5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(gridControlVendaParcelas, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        form1.setVOClassName("com.bakeryfactory.vendas.java.VendaCondicoesPagamentoVO");
        form1.setFunctionId("vendaCondicoesPagamento");
        form1.setLayout(new java.awt.GridBagLayout());

        lblNome.setLabel("Nome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        form1.add(lblNome, gridBagConstraints);

        textControl3.setAttributeName("nome");
        textControl3.setEnabled(false);
        textControl3.setMaxCharacters(50);
        textControl3.setRequired(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        form1.add(textControl3, gridBagConstraints);

        lblDescricao.setText("Descrição:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        form1.add(lblDescricao, gridBagConstraints);

        lblFaturamentoMin.setText("Faturamento Mínimo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        form1.add(lblFaturamentoMin, gridBagConstraints);

        numericControl5.setAttributeName("faturamentoMinimo");
        numericControl5.setDecimals(2);
        numericControl5.setEnabled(false);
        numericControl5.setRequired(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 30, 10);
        form1.add(numericControl5, gridBagConstraints);

        lblFaturamentoMax.setText("Faturamento Máximo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        form1.add(lblFaturamentoMax, gridBagConstraints);

        numericControl6.setAttributeName("faturamentoMaximo");
        numericControl6.setDecimals(2);
        numericControl6.setEnabled(false);
        numericControl6.setRequired(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 30, 10);
        form1.add(numericControl6, gridBagConstraints);

        lblIndiceCorrecao.setText("Índice Correção:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        form1.add(lblIndiceCorrecao, gridBagConstraints);

        numericControl7.setAttributeName("indiceCorrecao");
        numericControl7.setDecimals(2);
        numericControl7.setEnabled(false);
        numericControl7.setRequired(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 30, 10);
        form1.add(numericControl7, gridBagConstraints);

        lblDiasTolerancia.setText("Dias Tolerância:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        form1.add(lblDiasTolerancia, gridBagConstraints);

        numericControl8.setAttributeName("diasTolerancia");
        numericControl8.setEnabled(false);
        numericControl8.setRequired(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 30, 10);
        form1.add(numericControl8, gridBagConstraints);

        lblValorTolerancia.setText("Valor Tolerância:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        form1.add(lblValorTolerancia, gridBagConstraints);

        numericControl9.setAttributeName("valorTolerancia");
        numericControl9.setDecimals(2);
        numericControl9.setEnabled(false);
        numericControl9.setRequired(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 30, 10);
        form1.add(numericControl9, gridBagConstraints);

        lblPrazoMedio.setText("Prazo Médio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        form1.add(lblPrazoMedio, gridBagConstraints);

        numericControl10.setAttributeName("prazoMedio");
        numericControl10.setEnabled(false);
        numericControl10.setEnabledOnEdit(false);
        numericControl10.setEnabledOnInsert(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 30, 10);
        form1.add(numericControl10, gridBagConstraints);

        textAreaControl1.setAttributeName("descricao");
        textAreaControl1.setEnabled(false);
        textAreaControl1.setMaxCharacters(1000);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        form1.add(textAreaControl1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(form1, gridBagConstraints);

        jPanelVendaCondPagamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Venda Condições Pagamento"));
        jPanelVendaCondPagamento.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));
        jPanelVendaCondPagamento.add(editButtonCondPagto);
        jPanelVendaCondPagamento.add(reloadButtonCondPagto);
        jPanelVendaCondPagamento.add(saveButtonCondPagto);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanelVendaCondPagamento, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn5;
    private org.openswing.swing.client.DeleteButton deleteButtonCondParcela;
    private org.openswing.swing.client.EditButton editButtonCondPagto;
    private org.openswing.swing.client.EditButton editButtonCondParcela;
    private org.openswing.swing.form.client.Form form1;
    private org.openswing.swing.client.GridControl gridControlVendaParcelas;
    private org.openswing.swing.client.InsertButton insertButtonCondParcela;
    private org.openswing.swing.table.columns.client.IntegerColumn integerColumn3;
    private org.openswing.swing.table.columns.client.IntegerColumn integerColumn4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelVendaCondPagamento;
    private javax.swing.JPanel jPanelVendaCondParcelas;
    private org.openswing.swing.client.LabelControl lblDescricao;
    private org.openswing.swing.client.LabelControl lblDiasTolerancia;
    private org.openswing.swing.client.LabelControl lblFaturamentoMax;
    private org.openswing.swing.client.LabelControl lblFaturamentoMin;
    private org.openswing.swing.client.LabelControl lblIndiceCorrecao;
    private org.openswing.swing.client.LabelControl lblNome;
    private org.openswing.swing.client.LabelControl lblPrazoMedio;
    private org.openswing.swing.client.LabelControl lblValorTolerancia;
    private org.openswing.swing.client.NavigatorBar navigatorBarCondParcela;
    private org.openswing.swing.client.NumericControl numericControl10;
    private org.openswing.swing.client.NumericControl numericControl5;
    private org.openswing.swing.client.NumericControl numericControl6;
    private org.openswing.swing.client.NumericControl numericControl7;
    private org.openswing.swing.client.NumericControl numericControl8;
    private org.openswing.swing.client.NumericControl numericControl9;
    private org.openswing.swing.client.ReloadButton reloadButtonCondPagto;
    private org.openswing.swing.client.ReloadButton reloadButtonCondParcela;
    private org.openswing.swing.client.SaveButton saveButtonCondPagto;
    private org.openswing.swing.client.SaveButton saveButtonCondParcela;
    private org.openswing.swing.client.TextAreaControl textAreaControl1;
    private org.openswing.swing.client.TextControl textControl3;
    // End of variables declaration//GEN-END:variables
}
