/*
 * The MIT License
 *
 * Copyright 2016 Claudinei Aparecido Perboni - contact:cperbony@gmail.com.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.bakeryfactory.cadastros.cliente;

import com.bakeryfactory.cadastros.lookups.TipoAdmissaoLookup;
import com.bakeryfactory.cadastros.lookups.CargoLookup;
import com.bakeryfactory.cadastros.lookups.ContaContabilLookup;
import com.bakeryfactory.cadastros.lookups.NivelFormacaoLookup;
import com.bakeryfactory.cadastros.lookups.PessoaLookup;
import com.bakeryfactory.cadastros.lookups.SetorLookup;
import com.bakeryfactory.cadastros.lookups.SindicatoLookup;
import com.bakeryfactory.cadastros.lookups.SituacaoColaboradorLookup;
import com.bakeryfactory.cadastros.lookups.TipoColaboradorLookup;
import org.openswing.swing.mdi.client.InternalFrame;

/**
 *
 * @author Claudinei Aparecido Perboni - contact:cperbony@gmail.com
 */
public class ColaboradorDetalhe extends InternalFrame {

    private final PessoaLookup pessoaLookup;
    private final TipoColaboradorLookup tipoColaboraborLookup;
    private final SituacaoColaboradorLookup situacaoColaboradorLookup;
    private final TipoAdmissaoLookup tipoAdmissaoLookup;
    private final NivelFormacaoLookup nivelFormacaoLookup;
    private final CargoLookup cargoLookup;
    private final ContaContabilLookup contaContabilLookup;
    private final SindicatoLookup sindicatoLookup;
    private final SetorLookup setorLookup;

    /**
     * Creates new form ColaboradorDetalhe
     * @param controller
     */
    public ColaboradorDetalhe(ColaboradorDetalheController controller) {
        initComponents();

        form1.setFormController(controller);

        //Configuração Lookup Pessoa
        pessoaLookup = new PessoaLookup();
        codLookupControlPessoa.setLookupController(pessoaLookup);

        //Configuração Lookup Tipo Colaborador
        tipoColaboraborLookup = new TipoColaboradorLookup();
        codLookupControlTipo.setLookupController(tipoColaboraborLookup);

        //Configuração Lookup Tipo Situação Colaborador
        situacaoColaboradorLookup = new SituacaoColaboradorLookup();
        codLookupControlSituacao.setLookupController(situacaoColaboradorLookup);

        //Configuração Lookup Tipo Admissão
        tipoAdmissaoLookup = new TipoAdmissaoLookup();
        codLookupControlTipoAdmissao.setLookupController(tipoAdmissaoLookup);

        //Configuração Lookup Nivel Formação
        nivelFormacaoLookup = new NivelFormacaoLookup();
        codLookupControlNivelFormacao.setLookupController(nivelFormacaoLookup);

        //Configuração Lookup Nivel Cargo
        cargoLookup = new CargoLookup();
        codLookupControlCargo.setLookupController(cargoLookup);

        //Configuração Lookup Nivel Conta Contábil
        contaContabilLookup = new ContaContabilLookup();
        codLookupControlCargo.setLookupController(contaContabilLookup);

        //Configuração Lookup Nivel Setor
        setorLookup = new SetorLookup();
        codLookupControlSetor.setLookupController(setorLookup);

        //Configuração Lookup Nivel Sindicato
        sindicatoLookup = new SindicatoLookup();
        codLookupControlSindicato.setLookupController(sindicatoLookup);
    }

    /**
     *
     * @return FORM
     */
    public org.openswing.swing.form.client.Form getForm1() {
        return form1;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        editButton1 = new org.openswing.swing.client.EditButton();
        reloadButton1 = new org.openswing.swing.client.ReloadButton();
        saveButton1 = new org.openswing.swing.client.SaveButton();
        form1 = new org.openswing.swing.form.client.Form();
        jTabbedPaneDados = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblPessoa = new org.openswing.swing.client.LabelControl();
        codLookupControlPessoa = new org.openswing.swing.client.CodLookupControl();
        textControl6 = new org.openswing.swing.client.TextControl();
        lblTipo = new org.openswing.swing.client.LabelControl();
        codLookupControlTipo = new org.openswing.swing.client.CodLookupControl();
        textControl7 = new org.openswing.swing.client.TextControl();
        lblSituacao = new org.openswing.swing.client.LabelControl();
        codLookupControlSituacao = new org.openswing.swing.client.CodLookupControl();
        textControl5 = new org.openswing.swing.client.TextControl();
        lblTipoAdmissao = new org.openswing.swing.client.LabelControl();
        codLookupControlTipoAdmissao = new org.openswing.swing.client.CodLookupControl();
        textControl4 = new org.openswing.swing.client.TextControl();
        lblNivelFormacao = new org.openswing.swing.client.LabelControl();
        codLookupControlNivelFormacao = new org.openswing.swing.client.CodLookupControl();
        textControl8 = new org.openswing.swing.client.TextControl();
        lblCargo = new org.openswing.swing.client.LabelControl();
        codLookupControlCargo = new org.openswing.swing.client.CodLookupControl();
        textControl9 = new org.openswing.swing.client.TextControl();
        lblSetor = new org.openswing.swing.client.LabelControl();
        codLookupControlSetor = new org.openswing.swing.client.CodLookupControl();
        textControl10 = new org.openswing.swing.client.TextControl();
        lblContabilConta = new org.openswing.swing.client.LabelControl();
        codLookupControlContabilConta = new org.openswing.swing.client.CodLookupControl();
        textControl2 = new org.openswing.swing.client.TextControl();
        lblSindicato = new org.openswing.swing.client.LabelControl();
        codLookupControlSindicato = new org.openswing.swing.client.CodLookupControl();
        textControl3 = new org.openswing.swing.client.TextControl();
        lblDataCadastro = new org.openswing.swing.client.LabelControl();
        dateControl13 = new org.openswing.swing.client.DateControl();
        lblDataAdmissao = new org.openswing.swing.client.LabelControl();
        dateControl14 = new org.openswing.swing.client.DateControl();
        labelControl23 = new org.openswing.swing.client.LabelControl();
        dateControl15 = new org.openswing.swing.client.DateControl();
        labelControl24 = new org.openswing.swing.client.LabelControl();
        dateControl16 = new org.openswing.swing.client.DateControl();
        labelControl53 = new org.openswing.swing.client.LabelControl();
        dateControl45 = new org.openswing.swing.client.DateControl();
        lblDescontoPlanoSaúde = new org.openswing.swing.client.LabelControl();
        comboBoxControl37 = new org.openswing.swing.client.ComboBoxControl();
        lblSaiNaRais = new org.openswing.swing.client.LabelControl();
        comboBoxControl38 = new org.openswing.swing.client.ComboBoxControl();
        labelControl54 = new org.openswing.swing.client.LabelControl();
        textControl46 = new org.openswing.swing.client.TextControl();
        lblObservacao = new org.openswing.swing.client.LabelControl();
        textAreaControl1 = new org.openswing.swing.client.TextAreaControl();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblExameMedicoUltimo = new org.openswing.swing.client.LabelControl();
        dateControl26 = new org.openswing.swing.client.DateControl();
        dateControl27 = new org.openswing.swing.client.DateControl();
        lblExameMedicoVenc = new org.openswing.swing.client.LabelControl();
        jPanel5 = new javax.swing.JPanel();
        lblOcorrenciaSefip = new org.openswing.swing.client.LabelControl();
        numericControl41 = new org.openswing.swing.client.NumericControl();
        lblCategSefip = new org.openswing.swing.client.LabelControl();
        textControl39 = new org.openswing.swing.client.TextControl();
        lblCodDemissaoSefip = new org.openswing.swing.client.LabelControl();
        numericControl44 = new org.openswing.swing.client.NumericControl();
        jPanel6 = new javax.swing.JPanel();
        lblCodAdCaged = new org.openswing.swing.client.LabelControl();
        numericControl42 = new org.openswing.swing.client.NumericControl();
        lblCodDemCaged = new org.openswing.swing.client.LabelControl();
        numericControl43 = new org.openswing.swing.client.NumericControl();
        jPanel7 = new javax.swing.JPanel();
        lblFgtsOptante = new org.openswing.swing.client.LabelControl();
        comboBoxControl17 = new org.openswing.swing.client.ComboBoxControl();
        dateControl18 = new org.openswing.swing.client.DateControl();
        lblFgtsDataOpcao = new org.openswing.swing.client.LabelControl();
        numericControl19 = new org.openswing.swing.client.NumericControl();
        lblFgtsConta = new org.openswing.swing.client.LabelControl();
        jPanel8 = new javax.swing.JPanel();
        lblCtpsNumero = new org.openswing.swing.client.LabelControl();
        textControl33 = new org.openswing.swing.client.TextControl();
        lblCtpsSerie = new org.openswing.swing.client.LabelControl();
        textControl34 = new org.openswing.swing.client.TextControl();
        lblCtpsDatExp = new org.openswing.swing.client.LabelControl();
        dateControl35 = new org.openswing.swing.client.DateControl();
        lblCtpsUf = new org.openswing.swing.client.LabelControl();
        textControl36 = new org.openswing.swing.client.TextControl();
        jPanel9 = new javax.swing.JPanel();
        labelControl28 = new org.openswing.swing.client.LabelControl();
        comboBoxControl20 = new org.openswing.swing.client.ComboBoxControl();
        lblBanco = new org.openswing.swing.client.LabelControl();
        textControl21 = new org.openswing.swing.client.TextControl();
        lblAgencia = new org.openswing.swing.client.LabelControl();
        textControl22 = new org.openswing.swing.client.TextControl();
        lblDV1 = new org.openswing.swing.client.LabelControl();
        lblConta = new org.openswing.swing.client.LabelControl();
        textControl24 = new org.openswing.swing.client.TextControl();
        lblDV2 = new org.openswing.swing.client.LabelControl();
        textControl25 = new org.openswing.swing.client.TextControl();
        textControl26 = new org.openswing.swing.client.TextControl();
        jPanel10 = new javax.swing.JPanel();
        lblPisDataCadastro = new org.openswing.swing.client.LabelControl();
        dateControl28 = new org.openswing.swing.client.DateControl();
        lblPisNumero = new org.openswing.swing.client.LabelControl();
        textControl29 = new org.openswing.swing.client.TextControl();
        textControl30 = new org.openswing.swing.client.TextControl();
        lblPisBanco = new org.openswing.swing.client.LabelControl();
        lblPisAgencia = new org.openswing.swing.client.LabelControl();
        textControl31 = new org.openswing.swing.client.TextControl();
        lblPisAgenciaDigito = new org.openswing.swing.client.LabelControl();
        textControl32 = new org.openswing.swing.client.TextControl();
        jSeparator2 = new javax.swing.JSeparator();

        setTitle("Bakery Factory - Colaborador Detalhes");
        setPreferredSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Colaborador"));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel1.add(editButton1);
        jPanel1.add(reloadButton1);
        jPanel1.add(saveButton1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        form1.setVOClassName("com.t2tierp.cadastros.java.ColaboradorVO");
        form1.setFunctionId("colaborador");
        form1.setLayout(new java.awt.CardLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        lblPessoa.setLabel("Pessoa:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(lblPessoa, gridBagConstraints);

        codLookupControlPessoa.setAllowOnlyNumbers(true);
        codLookupControlPessoa.setAttributeName("pessoa.id");
        codLookupControlPessoa.setEnabled(false);
        codLookupControlPessoa.setRequired(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = -70;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(codLookupControlPessoa, gridBagConstraints);

        textControl6.setAttributeName("pessoa.nome");
        textControl6.setEnabled(false);
        textControl6.setEnabledOnEdit(false);
        textControl6.setEnabledOnInsert(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(textControl6, gridBagConstraints);

        lblTipo.setLabel("Tipo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(lblTipo, gridBagConstraints);

        codLookupControlTipo.setAllowOnlyNumbers(true);
        codLookupControlTipo.setAttributeName("tipoColaborador.id");
        codLookupControlTipo.setEnabled(false);
        codLookupControlTipo.setRequired(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = -70;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(codLookupControlTipo, gridBagConstraints);

        textControl7.setAttributeName("tipoColaborador.nome");
        textControl7.setEnabled(false);
        textControl7.setEnabledOnEdit(false);
        textControl7.setEnabledOnInsert(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(textControl7, gridBagConstraints);

        lblSituacao.setText("Situação:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(lblSituacao, gridBagConstraints);

        codLookupControlSituacao.setAllowOnlyNumbers(true);
        codLookupControlSituacao.setAttributeName("situacaoColaborador.id");
        codLookupControlSituacao.setEnabled(false);
        codLookupControlSituacao.setRequired(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(codLookupControlSituacao, gridBagConstraints);

        textControl5.setAttributeName("situacaoColaborador.nome");
        textControl5.setEnabled(false);
        textControl5.setEnabledOnEdit(false);
        textControl5.setEnabledOnInsert(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(textControl5, gridBagConstraints);

        lblTipoAdmissao.setText("Tipo Admissão:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(lblTipoAdmissao, gridBagConstraints);

        codLookupControlTipoAdmissao.setAttributeName("idtipoadmissao.id");
        codLookupControlTipoAdmissao.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(codLookupControlTipoAdmissao, gridBagConstraints);

        textControl4.setAttributeName("tipoAdmissao.nome");
        textControl4.setEnabled(false);
        textControl4.setEnabledOnEdit(false);
        textControl4.setEnabledOnInsert(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(textControl4, gridBagConstraints);

        lblNivelFormacao.setText("Nivel Formação:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(lblNivelFormacao, gridBagConstraints);

        codLookupControlNivelFormacao.setAllowOnlyNumbers(true);
        codLookupControlNivelFormacao.setAttributeName("nivelFormacao.id");
        codLookupControlNivelFormacao.setEnabled(false);
        codLookupControlNivelFormacao.setRequired(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(codLookupControlNivelFormacao, gridBagConstraints);

        textControl8.setAttributeName("nivelFormacao.nome");
        textControl8.setEnabled(false);
        textControl8.setEnabledOnEdit(false);
        textControl8.setEnabledOnInsert(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(textControl8, gridBagConstraints);

        lblCargo.setLabel("Cargo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(lblCargo, gridBagConstraints);

        codLookupControlCargo.setAllowOnlyNumbers(true);
        codLookupControlCargo.setAttributeName("cargo.id");
        codLookupControlCargo.setEnabled(false);
        codLookupControlCargo.setRequired(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(codLookupControlCargo, gridBagConstraints);

        textControl9.setAttributeName("cargo.nome");
        textControl9.setEnabled(false);
        textControl9.setEnabledOnEdit(false);
        textControl9.setEnabledOnInsert(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(textControl9, gridBagConstraints);

        lblSetor.setLabel("Setor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(lblSetor, gridBagConstraints);

        codLookupControlSetor.setAllowOnlyNumbers(true);
        codLookupControlSetor.setAttributeName("setor.id");
        codLookupControlSetor.setEnabled(false);
        codLookupControlSetor.setRequired(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(codLookupControlSetor, gridBagConstraints);

        textControl10.setAttributeName("setor.nome");
        textControl10.setEnabled(false);
        textControl10.setEnabledOnEdit(false);
        textControl10.setEnabledOnInsert(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(textControl10, gridBagConstraints);

        lblContabilConta.setText("Contábil Conta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(lblContabilConta, gridBagConstraints);

        codLookupControlContabilConta.setAllowOnlyNumbers(true);
        codLookupControlContabilConta.setAttributeName("contabilConta.id");
        codLookupControlContabilConta.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(codLookupControlContabilConta, gridBagConstraints);

        textControl2.setAttributeName("contabilConta.descricao");
        textControl2.setEnabled(false);
        textControl2.setEnabledOnEdit(false);
        textControl2.setEnabledOnInsert(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(textControl2, gridBagConstraints);

        lblSindicato.setLabel("Sindicato:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(lblSindicato, gridBagConstraints);

        codLookupControlSindicato.setAllowOnlyNumbers(true);
        codLookupControlSindicato.setAttributeName("sindicato.id");
        codLookupControlSindicato.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(codLookupControlSindicato, gridBagConstraints);

        textControl3.setAttributeName("sindicato.nome");
        textControl3.setEnabled(false);
        textControl3.setEnabledOnEdit(false);
        textControl3.setEnabledOnInsert(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(textControl3, gridBagConstraints);

        lblDataCadastro.setLabel("Data Cadastro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(lblDataCadastro, gridBagConstraints);

        dateControl13.setAttributeName("dataCadastro");
        dateControl13.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(dateControl13, gridBagConstraints);

        lblDataAdmissao.setText("Data Admissão:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(lblDataAdmissao, gridBagConstraints);

        dateControl14.setAttributeName("dataAdmissao");
        dateControl14.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(dateControl14, gridBagConstraints);

        labelControl23.setText("Vencimento Férias:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(labelControl23, gridBagConstraints);

        dateControl15.setAttributeName("vencimentoFerias");
        dateControl15.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(dateControl15, gridBagConstraints);

        labelControl24.setText("Data Transferência:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(labelControl24, gridBagConstraints);

        dateControl16.setAttributeName("dataTransferencia");
        dateControl16.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(dateControl16, gridBagConstraints);

        labelControl53.setText("Data Demissão:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(labelControl53, gridBagConstraints);

        dateControl45.setAttributeName("dataDemissao");
        dateControl45.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(dateControl45, gridBagConstraints);

        lblDescontoPlanoSaúde.setText("Desconto Plano Saúde:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(lblDescontoPlanoSaúde, gridBagConstraints);

        comboBoxControl37.setAttributeName("descontoPlanoSaude");
        comboBoxControl37.setDomainId("simnao");
        comboBoxControl37.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(comboBoxControl37, gridBagConstraints);

        lblSaiNaRais.setLabel("Sai Na Rais:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(lblSaiNaRais, gridBagConstraints);

        comboBoxControl38.setAttributeName("saiNaRais");
        comboBoxControl38.setDomainId("simnao");
        comboBoxControl38.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(comboBoxControl38, gridBagConstraints);

        labelControl54.setText("Código Turma Ponto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(labelControl54, gridBagConstraints);

        textControl46.setAttributeName("codigoTurmaPonto");
        textControl46.setEnabled(false);
        textControl46.setMaxCharacters(5);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(textControl46, gridBagConstraints);

        lblObservacao.setText("Observação:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(lblObservacao, gridBagConstraints);

        textAreaControl1.setAttributeName("observacao");
        textAreaControl1.setEnabled(false);
        textAreaControl1.setMaxCharacters(1000);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel2.add(textAreaControl1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jSeparator1, gridBagConstraints);

        jTabbedPaneDados.addTab("Dados Principais", jPanel2);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Exame Médico"));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        lblExameMedicoUltimo.setText("Exame Médico Último:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel4.add(lblExameMedicoUltimo, gridBagConstraints);

        dateControl26.setAttributeName("exameMedicoUltimo");
        dateControl26.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel4.add(dateControl26, gridBagConstraints);

        dateControl27.setAttributeName("exameMedicoVencimento");
        dateControl27.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel4.add(dateControl27, gridBagConstraints);

        lblExameMedicoVenc.setText("Exame Médico Vencimento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel4.add(lblExameMedicoVenc, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel3.add(jPanel4, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Sefip"));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        lblOcorrenciaSefip.setLabel("Ocorrencia Sefip:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel5.add(lblOcorrenciaSefip, gridBagConstraints);

        numericControl41.setAttributeName("ocorrenciaSefip");
        numericControl41.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel5.add(numericControl41, gridBagConstraints);

        lblCategSefip.setLabel("Categoria Sefip:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel5.add(lblCategSefip, gridBagConstraints);

        textControl39.setAttributeName("categoriaSefip");
        textControl39.setEnabled(false);
        textControl39.setMaxCharacters(2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel5.add(textControl39, gridBagConstraints);

        lblCodDemissaoSefip.setText("Código Demissão Sefip:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel5.add(lblCodDemissaoSefip, gridBagConstraints);

        numericControl44.setAttributeName("codigoDemissaoSefip");
        numericControl44.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel5.add(numericControl44, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel3.add(jPanel5, gridBagConstraints);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Caged"));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        lblCodAdCaged.setText("Código Admissão Caged:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel6.add(lblCodAdCaged, gridBagConstraints);

        numericControl42.setAttributeName("codigoAdmissaoCaged");
        numericControl42.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel6.add(numericControl42, gridBagConstraints);

        lblCodDemCaged.setText("Código Demissão Caged:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel6.add(lblCodDemCaged, gridBagConstraints);

        numericControl43.setAttributeName("codigoDemissaoCaged");
        numericControl43.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel6.add(numericControl43, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel3.add(jPanel6, gridBagConstraints);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("FGTS"));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        lblFgtsOptante.setLabel("Fgts Optante:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel7.add(lblFgtsOptante, gridBagConstraints);

        comboBoxControl17.setAttributeName("fgtsOptante");
        comboBoxControl17.setDomainId("simnao");
        comboBoxControl17.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel7.add(comboBoxControl17, gridBagConstraints);

        dateControl18.setAttributeName("fgtsDataOpcao");
        dateControl18.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel7.add(dateControl18, gridBagConstraints);

        lblFgtsDataOpcao.setText("Fgts Data Opção:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel7.add(lblFgtsDataOpcao, gridBagConstraints);

        numericControl19.setAttributeName("fgtsConta");
        numericControl19.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel7.add(numericControl19, gridBagConstraints);

        lblFgtsConta.setLabel("Fgts Conta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel7.add(lblFgtsConta, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel3.add(jPanel7, gridBagConstraints);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Carteira Profissional"));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        lblCtpsNumero.setText("Ctps Número:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel8.add(lblCtpsNumero, gridBagConstraints);

        textControl33.setAttributeName("ctpsNumero");
        textControl33.setEnabled(false);
        textControl33.setMaxCharacters(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel8.add(textControl33, gridBagConstraints);

        lblCtpsSerie.setText("Ctps Série:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel8.add(lblCtpsSerie, gridBagConstraints);

        textControl34.setAttributeName("ctpsSerie");
        textControl34.setEnabled(false);
        textControl34.setMaxCharacters(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel8.add(textControl34, gridBagConstraints);

        lblCtpsDatExp.setLabel("Ctps Data Expedicao:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel8.add(lblCtpsDatExp, gridBagConstraints);

        dateControl35.setAttributeName("ctpsDataExpedicao");
        dateControl35.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel8.add(dateControl35, gridBagConstraints);

        lblCtpsUf.setLabel("Ctps Uf:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel8.add(lblCtpsUf, gridBagConstraints);

        textControl36.setAttributeName("ctpsUf");
        textControl36.setEnabled(false);
        textControl36.setMaxCharacters(2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel8.add(textControl36, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel3.add(jPanel8, gridBagConstraints);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Pagamento"));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        labelControl28.setLabel("Pagamento Forma:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel9.add(labelControl28, gridBagConstraints);

        comboBoxControl20.setAttributeName("pagamentoForma");
        comboBoxControl20.setDomainId("colaboradorFormaPagamento");
        comboBoxControl20.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel9.add(comboBoxControl20, gridBagConstraints);

        lblBanco.setLabel("Banco:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel9.add(lblBanco, gridBagConstraints);

        textControl21.setAttributeName("pagamentoBanco");
        textControl21.setEnabled(false);
        textControl21.setMaxCharacters(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel9.add(textControl21, gridBagConstraints);

        lblAgencia.setText("Agência:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel9.add(lblAgencia, gridBagConstraints);

        textControl22.setAttributeName("pagamentoAgencia");
        textControl22.setEnabled(false);
        textControl22.setMaxCharacters(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel9.add(textControl22, gridBagConstraints);

        lblDV1.setLabel("DV:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel9.add(lblDV1, gridBagConstraints);

        lblConta.setLabel("Conta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel9.add(lblConta, gridBagConstraints);

        textControl24.setAttributeName("pagamentoConta");
        textControl24.setEnabled(false);
        textControl24.setMaxCharacters(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel9.add(textControl24, gridBagConstraints);

        lblDV2.setLabel("DV:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel9.add(lblDV2, gridBagConstraints);

        textControl25.setAttributeName("pagamentoConta");
        textControl25.setEnabled(false);
        textControl25.setMaxCharacters(1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel9.add(textControl25, gridBagConstraints);

        textControl26.setAttributeName("pagamentoConta");
        textControl26.setEnabled(false);
        textControl26.setMaxCharacters(1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel9.add(textControl26, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel3.add(jPanel9, gridBagConstraints);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("PIS"));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        lblPisDataCadastro.setLabel("Pis Data Cadastro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel10.add(lblPisDataCadastro, gridBagConstraints);

        dateControl28.setAttributeName("pisDataCadastro");
        dateControl28.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel10.add(dateControl28, gridBagConstraints);

        lblPisNumero.setText("Pis Número:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel10.add(lblPisNumero, gridBagConstraints);

        textControl29.setAttributeName("pisNumero");
        textControl29.setEnabled(false);
        textControl29.setMaxCharacters(12);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel10.add(textControl29, gridBagConstraints);

        textControl30.setAttributeName("pisBanco");
        textControl30.setEnabled(false);
        textControl30.setMaxCharacters(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel10.add(textControl30, gridBagConstraints);

        lblPisBanco.setLabel("Pis Banco:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel10.add(lblPisBanco, gridBagConstraints);

        lblPisAgencia.setText("Pis Agência:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel10.add(lblPisAgencia, gridBagConstraints);

        textControl31.setAttributeName("pisAgencia");
        textControl31.setEnabled(false);
        textControl31.setMaxCharacters(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel10.add(textControl31, gridBagConstraints);

        lblPisAgenciaDigito.setText("Pis Agência Dígito:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel10.add(lblPisAgenciaDigito, gridBagConstraints);

        textControl32.setAttributeName("pisAgencia");
        textControl32.setEnabled(false);
        textControl32.setMaxCharacters(1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel10.add(textControl32, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel3.add(jPanel10, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jSeparator2, gridBagConstraints);

        jTabbedPaneDados.addTab("Outras Informações", jPanel3);

        form1.add(jTabbedPaneDados, "card2");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(form1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.client.CodLookupControl codLookupControlCargo;
    private org.openswing.swing.client.CodLookupControl codLookupControlContabilConta;
    private org.openswing.swing.client.CodLookupControl codLookupControlNivelFormacao;
    private org.openswing.swing.client.CodLookupControl codLookupControlPessoa;
    private org.openswing.swing.client.CodLookupControl codLookupControlSetor;
    private org.openswing.swing.client.CodLookupControl codLookupControlSindicato;
    private org.openswing.swing.client.CodLookupControl codLookupControlSituacao;
    private org.openswing.swing.client.CodLookupControl codLookupControlTipo;
    private org.openswing.swing.client.CodLookupControl codLookupControlTipoAdmissao;
    private org.openswing.swing.client.ComboBoxControl comboBoxControl17;
    private org.openswing.swing.client.ComboBoxControl comboBoxControl20;
    private org.openswing.swing.client.ComboBoxControl comboBoxControl37;
    private org.openswing.swing.client.ComboBoxControl comboBoxControl38;
    private org.openswing.swing.client.DateControl dateControl13;
    private org.openswing.swing.client.DateControl dateControl14;
    private org.openswing.swing.client.DateControl dateControl15;
    private org.openswing.swing.client.DateControl dateControl16;
    private org.openswing.swing.client.DateControl dateControl18;
    private org.openswing.swing.client.DateControl dateControl26;
    private org.openswing.swing.client.DateControl dateControl27;
    private org.openswing.swing.client.DateControl dateControl28;
    private org.openswing.swing.client.DateControl dateControl35;
    private org.openswing.swing.client.DateControl dateControl45;
    private org.openswing.swing.client.EditButton editButton1;
    private org.openswing.swing.form.client.Form form1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPaneDados;
    private org.openswing.swing.client.LabelControl labelControl23;
    private org.openswing.swing.client.LabelControl labelControl24;
    private org.openswing.swing.client.LabelControl labelControl28;
    private org.openswing.swing.client.LabelControl labelControl53;
    private org.openswing.swing.client.LabelControl labelControl54;
    private org.openswing.swing.client.LabelControl lblAgencia;
    private org.openswing.swing.client.LabelControl lblBanco;
    private org.openswing.swing.client.LabelControl lblCargo;
    private org.openswing.swing.client.LabelControl lblCategSefip;
    private org.openswing.swing.client.LabelControl lblCodAdCaged;
    private org.openswing.swing.client.LabelControl lblCodDemCaged;
    private org.openswing.swing.client.LabelControl lblCodDemissaoSefip;
    private org.openswing.swing.client.LabelControl lblConta;
    private org.openswing.swing.client.LabelControl lblContabilConta;
    private org.openswing.swing.client.LabelControl lblCtpsDatExp;
    private org.openswing.swing.client.LabelControl lblCtpsNumero;
    private org.openswing.swing.client.LabelControl lblCtpsSerie;
    private org.openswing.swing.client.LabelControl lblCtpsUf;
    private org.openswing.swing.client.LabelControl lblDV1;
    private org.openswing.swing.client.LabelControl lblDV2;
    private org.openswing.swing.client.LabelControl lblDataAdmissao;
    private org.openswing.swing.client.LabelControl lblDataCadastro;
    private org.openswing.swing.client.LabelControl lblDescontoPlanoSaúde;
    private org.openswing.swing.client.LabelControl lblExameMedicoUltimo;
    private org.openswing.swing.client.LabelControl lblExameMedicoVenc;
    private org.openswing.swing.client.LabelControl lblFgtsConta;
    private org.openswing.swing.client.LabelControl lblFgtsDataOpcao;
    private org.openswing.swing.client.LabelControl lblFgtsOptante;
    private org.openswing.swing.client.LabelControl lblNivelFormacao;
    private org.openswing.swing.client.LabelControl lblObservacao;
    private org.openswing.swing.client.LabelControl lblOcorrenciaSefip;
    private org.openswing.swing.client.LabelControl lblPessoa;
    private org.openswing.swing.client.LabelControl lblPisAgencia;
    private org.openswing.swing.client.LabelControl lblPisAgenciaDigito;
    private org.openswing.swing.client.LabelControl lblPisBanco;
    private org.openswing.swing.client.LabelControl lblPisDataCadastro;
    private org.openswing.swing.client.LabelControl lblPisNumero;
    private org.openswing.swing.client.LabelControl lblSaiNaRais;
    private org.openswing.swing.client.LabelControl lblSetor;
    private org.openswing.swing.client.LabelControl lblSindicato;
    private org.openswing.swing.client.LabelControl lblSituacao;
    private org.openswing.swing.client.LabelControl lblTipo;
    private org.openswing.swing.client.LabelControl lblTipoAdmissao;
    private org.openswing.swing.client.NumericControl numericControl19;
    private org.openswing.swing.client.NumericControl numericControl41;
    private org.openswing.swing.client.NumericControl numericControl42;
    private org.openswing.swing.client.NumericControl numericControl43;
    private org.openswing.swing.client.NumericControl numericControl44;
    private org.openswing.swing.client.ReloadButton reloadButton1;
    private org.openswing.swing.client.SaveButton saveButton1;
    private org.openswing.swing.client.TextAreaControl textAreaControl1;
    private org.openswing.swing.client.TextControl textControl10;
    private org.openswing.swing.client.TextControl textControl2;
    private org.openswing.swing.client.TextControl textControl21;
    private org.openswing.swing.client.TextControl textControl22;
    private org.openswing.swing.client.TextControl textControl24;
    private org.openswing.swing.client.TextControl textControl25;
    private org.openswing.swing.client.TextControl textControl26;
    private org.openswing.swing.client.TextControl textControl29;
    private org.openswing.swing.client.TextControl textControl3;
    private org.openswing.swing.client.TextControl textControl30;
    private org.openswing.swing.client.TextControl textControl31;
    private org.openswing.swing.client.TextControl textControl32;
    private org.openswing.swing.client.TextControl textControl33;
    private org.openswing.swing.client.TextControl textControl34;
    private org.openswing.swing.client.TextControl textControl36;
    private org.openswing.swing.client.TextControl textControl39;
    private org.openswing.swing.client.TextControl textControl4;
    private org.openswing.swing.client.TextControl textControl46;
    private org.openswing.swing.client.TextControl textControl5;
    private org.openswing.swing.client.TextControl textControl6;
    private org.openswing.swing.client.TextControl textControl7;
    private org.openswing.swing.client.TextControl textControl8;
    private org.openswing.swing.client.TextControl textControl9;
    // End of variables declaration//GEN-END:variables
}
