/*
 * The MIT License
 *
 * Copyright 2016 Claudinei Aparecido Perboni - contact:cperbony@gmail.com.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.bakeryfactory.cadastros.cliente;

import org.openswing.swing.client.GridControl;
import org.openswing.swing.mdi.client.InternalFrame;

/**
 *
 * @author Claudinei Aparecido Perboni - contact:cperbony@gmail.com
 */
public class ColaboradorGrid extends InternalFrame {

    /**
     * Creates new form ColaboradorGrid
     */
    public ColaboradorGrid(ColaboradorGridController controller) {
        initComponents();
        gridControl1.setController(controller);
        gridControl1.setGridDataLocator(controller);
    }
    
    public GridControl getGrid1(){
        return gridControl1;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        insertButton1 = new org.openswing.swing.client.InsertButton();
        deleteButton1 = new org.openswing.swing.client.DeleteButton();
        reloadButton1 = new org.openswing.swing.client.ReloadButton();
        navigatorBar1 = new org.openswing.swing.client.NavigatorBar();
        gridControl1 = new org.openswing.swing.client.GridControl();
        textColumnNome = new org.openswing.swing.table.columns.client.TextColumn();
        textColumnSituacao = new org.openswing.swing.table.columns.client.TextColumn();
        textColumnTipo = new org.openswing.swing.table.columns.client.TextColumn();
        textColumnCargo = new org.openswing.swing.table.columns.client.TextColumn();
        textColumnSetor = new org.openswing.swing.table.columns.client.TextColumn();
        dateColumnDateCadastro = new org.openswing.swing.table.columns.client.DateColumn();
        dateColumnDataAdmissao = new org.openswing.swing.table.columns.client.DateColumn();
        dateColumnDataDemissao = new org.openswing.swing.table.columns.client.DateColumn();

        setTitle("Bakery Factory - Cadastro Colaboradores");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro Colaboradores"));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel1.add(insertButton1);
        jPanel1.add(deleteButton1);
        jPanel1.add(reloadButton1);
        jPanel1.add(navigatorBar1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        gridControl1.setDeleteButton(deleteButton1);
        gridControl1.setFunctionId("colaborador");
        gridControl1.setInsertButton(insertButton1);
        gridControl1.setNavBar(navigatorBar1);
        gridControl1.setReloadButton(reloadButton1);
        gridControl1.setValueObjectClassName("com.bakeryfactory.cadastros.java.ColaboradorVO");
        gridControl1.getColumnContainer().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        textColumnNome.setColumnFilterable(true);
        textColumnNome.setColumnName("pessoa.nome");
        textColumnNome.setColumnSortable(true);
        textColumnNome.setHeaderColumnName("Nome");
        textColumnNome.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        textColumnNome.setPreferredWidth(200);
        gridControl1.getColumnContainer().add(textColumnNome);

        textColumnSituacao.setColumnFilterable(true);
        textColumnSituacao.setColumnName("situacaoColaborador.nome");
        textColumnSituacao.setColumnSortable(true);
        textColumnSituacao.setHeaderColumnName("Situacao");
        textColumnSituacao.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridControl1.getColumnContainer().add(textColumnSituacao);

        textColumnTipo.setColumnFilterable(true);
        textColumnTipo.setColumnName("tipoColaborador.nome");
        textColumnTipo.setColumnSortable(true);
        textColumnTipo.setHeaderColumnName("Tipo");
        textColumnTipo.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridControl1.getColumnContainer().add(textColumnTipo);

        textColumnCargo.setColumnFilterable(true);
        textColumnCargo.setColumnName("cargo.nome");
        textColumnCargo.setColumnSortable(true);
        textColumnCargo.setHeaderColumnName("Cargo");
        textColumnCargo.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        textColumnCargo.setPreferredWidth(150);
        gridControl1.getColumnContainer().add(textColumnCargo);

        textColumnSetor.setColumnFilterable(true);
        textColumnSetor.setColumnName("setor.nome");
        textColumnSetor.setColumnSortable(true);
        textColumnSetor.setHeaderColumnName("Setor");
        textColumnSetor.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        textColumnSetor.setPreferredWidth(150);
        gridControl1.getColumnContainer().add(textColumnSetor);

        dateColumnDateCadastro.setColumnFilterable(true);
        dateColumnDateCadastro.setColumnName("dataCadastro");
        dateColumnDateCadastro.setColumnSortable(true);
        dateColumnDateCadastro.setHeaderColumnName("Data Cadastro");
        dateColumnDateCadastro.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridControl1.getColumnContainer().add(dateColumnDateCadastro);

        dateColumnDataAdmissao.setColumnFilterable(true);
        dateColumnDataAdmissao.setColumnName("dataAdmissao");
        dateColumnDataAdmissao.setColumnSortable(true);
        dateColumnDataAdmissao.setHeaderColumnName("Data Admissao");
        dateColumnDataAdmissao.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridControl1.getColumnContainer().add(dateColumnDataAdmissao);

        dateColumnDataDemissao.setColumnFilterable(true);
        dateColumnDataDemissao.setColumnName("dataDemissao");
        dateColumnDataDemissao.setColumnSortable(true);
        dateColumnDataDemissao.setHeaderColumnName("Data Demissao");
        dateColumnDataDemissao.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridControl1.getColumnContainer().add(dateColumnDataDemissao);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(gridControl1, gridBagConstraints);
        gridControl1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.table.columns.client.DateColumn dateColumnDataAdmissao;
    private org.openswing.swing.table.columns.client.DateColumn dateColumnDataDemissao;
    private org.openswing.swing.table.columns.client.DateColumn dateColumnDateCadastro;
    private org.openswing.swing.client.DeleteButton deleteButton1;
    private org.openswing.swing.client.GridControl gridControl1;
    private org.openswing.swing.client.InsertButton insertButton1;
    private javax.swing.JPanel jPanel1;
    private org.openswing.swing.client.NavigatorBar navigatorBar1;
    private org.openswing.swing.client.ReloadButton reloadButton1;
    private org.openswing.swing.table.columns.client.TextColumn textColumnCargo;
    private org.openswing.swing.table.columns.client.TextColumn textColumnNome;
    private org.openswing.swing.table.columns.client.TextColumn textColumnSetor;
    private org.openswing.swing.table.columns.client.TextColumn textColumnSituacao;
    private org.openswing.swing.table.columns.client.TextColumn textColumnTipo;
    // End of variables declaration//GEN-END:variables
}
